baseurl =  # Include trailing slash
title = "Tom Informativo"
theme = "newsroom"
author = "Sapiens TJ"
canonifyurls = true
defaultContentLanguage = "pt"
paginate = 5

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true # change to true to enable inclusion of rawHTML and math functions
    xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    tabWidth = 2


[permalinks]
  post = '/:2006/:01/:title/'
    

# If you want to use disqus, uncomment the line below
# disqusShortname = "yourdiscussshortname"

[params]
  languageCode = "pt"
  dateFormat = "02 Jan 2006"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "@sapienstj" # twitter handle e.g @weru
  # mainSections = ["blog", "docs"] see https://gohugo.io/functions/where/#mainsections
  # uncomment the line below will disable darkmode by default.
  # uncomment and set value below to either "light" or "dark" to make default mode dark.
  # defaultMode = "" # Note that the UI control for toggling darkmode will remain in place. This way, the user can decide which mode they would like to use while browsing your website
logo = "/images/logo.svg" # if the value is an empty string, the site title will be shown instead

faviconsDir = "images/icons/" # with a trailing slash
blogDir = "post" # edit
