backend:
  name: git-gateway
  branch: main
media_folder: static/images/
public_folder: /images/
locale: 'pt'
collections:
  - label: "Posts"
    name: "post"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Data", name: "date", widget: "date" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagem", name: "cover", widget: "image", optional: true}
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", optional: true}
      - { label: "Destaque", name: "highlight", widget: "boolean", optional: true}
      - { label: "Conteúdo", name: "body", widget: "markdown" }